### ISSUE TITLE
out of source ./configure script fails with: IOError: [Errno 2] No such file or directory: u'../libpqxx/include/pqxx/config.h'

### ISSUE THREAD

**Issue by rocksolidwebdesign** [jtv/libpqxx#29]
when doing an out of source build as of 3f386376774b19e22e9b84403601c2df48f3b2b0 i.e. latest master, the following error occurs

```
Traceback (most recent call last):
  File "../libpqxx/tools/splitconfig", line 182, in <module>
    main()
  File "../libpqxx/tools/splitconfig", line 171, in main
    original_header = read_header(args.sourcetree, 'include/pqxx/config.h')
  File "../libpqxx/tools/splitconfig", line 73, in read_header
    return read_lines(os.path.join(source_tree, filename))
  File "../libpqxx/tools/splitconfig", line 41, in read_lines
    with codecs.open(path, encoding='ascii') as stream:
  File "/usr/lib/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: u'../libpqxx/include/pqxx/config.h'
```

when building inside the main source tree, this error does not occur

here are steps to reproduce and the full output

```
$ git clone https://github.com/jtv/libpqxx
Cloning into 'libpqxx'...
remote: Counting objects: 22598, done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 22598 (delta 10), reused 6 (delta 3), pack-reused 22571
Receiving objects: 100% (22598/22598), 4.56 MiB | 2.93 MiB/s, done.
Resolving deltas: 100% (18238/18238), done.
Checking connectivity... done.

$ mkdir libpqxx_build
$ cd libpqxx_build
$ ../libpqxx/configure
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking whether g++ supports C++11 features by default... no
checking whether g++ supports C++11 features with -std=gnu++11... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking whether make supports nested variables... yes
checking dependency style of g++... gcc3
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ accepts -g... (cached) yes
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether make sets $(MAKE)... (cached) yes
checking for mkdir... /bin/mkdir
checking for pkg-config... /usr/bin/pkg-config
checking for doxygen... no
checking for dot... YES
checking for xmlto... no
checking whether to enable maintainer-specific portions of Makefiles... no
checking maintainer mode... 
checking g++ visibility attribute... yes
checking g++ const attribute... yes
checking C++14 deprecation attribute... yes
checking g++ pure attribute... yes
checking for C++17 std::optional support... no
checking for experimental C++17 std::optional support... no
checking for pg_config... /usr/bin/pg_config
configure: using PostgreSQL headers at /usr/include/postgresql
configure: using PostgreSQL libraries at /usr/lib/x86_64-linux-gnu
checking for ANSI C header files... (cached) yes
checking for library containing select... none required
checking /usr/include/postgresql/libpq-fe.h usability... yes
checking /usr/include/postgresql/libpq-fe.h presence... yes
checking for /usr/include/postgresql/libpq-fe.h... yes
checking for ability to compile source files using libpq... yes
checking for main in -lpq... yes
checking for PQexec in -lpq... yes
checking for correct C++ linkage of basic libpq functions... yes
checking for C++11 support... checking that type of libpq's Oid is as expected... yes
checking for strerror_r... yes
checking for GNU-style strerror_r... yes
checking for strlcpy... no
checking for working <sys/select.h>... yes
checking for poll()... yes
checking if select() accepts NULL fdsets... yes
checking whether make sets $(MAKE)... (cached) yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config/Makefile
config.status: creating doc/Makefile
config.status: creating doc/Doxyfile
config.status: creating src/Makefile
config.status: creating test/Makefile
config.status: creating test/unit/Makefile
config.status: creating tools/Makefile
config.status: creating win32/Makefile
config.status: creating include/Makefile
config.status: creating include/pqxx/Makefile
config.status: creating libpqxx.pc
config.status: creating pqxx-config
config.status: creating include/pqxx/config.h
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing configitems commands
Traceback (most recent call last):
  File "../libpqxx/tools/splitconfig", line 182, in <module>
    main()
  File "../libpqxx/tools/splitconfig", line 171, in main
    original_header = read_header(args.sourcetree, 'include/pqxx/config.h')
  File "../libpqxx/tools/splitconfig", line 73, in read_header
    return read_lines(os.path.join(source_tree, filename))
  File "../libpqxx/tools/splitconfig", line 41, in read_lines
    with codecs.open(path, encoding='ascii') as stream:
  File "/usr/lib/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: u'../libpqxx/include/pqxx/config.h'
```

**Comment by jtv** [comment]
Right — we never went to the effort to support out-of-tree builds.  So it's not surprising that there should be problems.

That said, I think I've got this one error fixed now, so you can get a successful out-of-tree build.  I'm working on the next error, which happens when trying to run the tests.
